config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'landings/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  get "details" => "users#user_profile",   as: :user_profile_users
  resources :users, only: [:update]

  resources :academies do
    resources :assignments
    collection do
      get :academies_lists
      get :registration_list
    end
    member do
      get :send_joining_request
      get :approve_registration_request
      delete :remove_registration_request
      delete :remove_users
    end
  end

  resources :payments do
    collection do
      post :new_payment
    end
  end

  resources :portfolios do 
    member do 
      get :fetch_current_price
      get :change_status
    end
  end

  resources :companies do
    resources :purchases
    resources :sales 
  end
  
  resources :articles 
  resources :landings, path: "/" do
    collection do
      post :search  
    end
  end


  root 'landings#index'
end

app/models/academy.rb
class Academy < ActiveRecord::Base # :nodoc:
  has_one :subscription, dependent: :destroy
  has_one :owner, through: :subscription, foreign_key: 'institution_id',
                  source: :institution, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :moderators, -> { where("registrations.reg_type = 'Institution'") },
           through: :registrations, source: :user, dependent: :destroy
  has_many :students, -> { where("registrations.reg_type = 'Standard'") },
           through: :registrations, source: :user, dependent: :destroy
  has_many :assignments, dependent: :destroy

  validates_uniqueness_of :name
  accepts_nested_attributes_for :subscription, allow_destroy: true
end

app/controllers/academies_controller.rb
# rubocop:disable Metrics/AbcSize
class AcademiesController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:search].present?
      search = params[:search].downcase
      @academies = Academy.where('lower(name) LIKE ?
                                OR lower(description) LIKE ?',
                                 "%#{search}%", "%#{search}%")
    else
      @academies = Academy.all
    end
  end

  def new
    @academy = Academy.new
    @academy.build_subscription
  end

  def create
    academy = Academy.new(academy_permitted_params)
    if academy.save
      msg = 'Academy created successfully.'
      path = new_academy_payment_path(academy)
    else
      msg = academy.errors.full_messages.first
      path = :back
    end
    flash[:notice] = msg
    redirect_to path
  end

  def show
    @academy = Academy.includes(:registrations).find(params[:id])
    @assignments = @academy.assignments
    @students = @academy.students.where("status = 'approve'")
    @moderators = @academy.moderators.where("status = 'approve'")
    @student_requests = current_user.registrations.where(
      reg_type: 'Standard', status: 'pending')
    @moderator_requests = current_user.registrations.where(
      reg_type: 'Institution', status: 'pending')
  end

  def edit
    @academy = Academy.find(params[:id])
  end

  def update
    academy = Academy.find(params[:id])
    if academy.update_attributes(academy_permitted_params)
      msg = 'Academy information updated successfully.'
      path = academies_path
    else
      msg = academy.errors.full_messages.first
      path = :back
    end
    flash[:notice] = msg
    redirect_to path
  end

  def academies_lists
    @academies = Academy.all
  end

  def send_joining_request
    academy = Academy.find(params[:id])
    registration = Registration.create(user_id: current_user.id,
                                       academy_id: academy.id,
                                       reg_type: current_user.type)
    if current_user.is_institution_user?
      UserMailer.moderator_registration_request(registration).deliver
    else
      UserMailer.registration_request(registration).deliver
    end
    flash[:notice] = 'Your request delivered successfully'
    redirect_to :back
  end

  def registration_list
    if current_user.is_institution_user?
      @standard_registrations = current_user.academies.map(&:registrations).flatten.select { |reg| reg.reg_type == 'Standard' }.sort_by { |e| e[:created_at] }.reverse
      @institution_registrations = current_user.academies.map(&:registrations).flatten.select { |reg| reg.reg_type == 'Institution' }.sort_by { |e| e[:created_at] }.reverse
    else
      flash[:notice] = 'Please login as Insitutional User.'
      redirect_to root_path
    end
  end

  def approve_registration_request
    registration = Registration.find(params[:id])
    registration.status = 'approve'
    registration.save
    registration_list
    flash[:notice] = 'Registration request approved successfully'
  end

  def remove_registration_request
    registration = Registration.find(params[:id])
    registration.destroy
    registration_list
    flash[:notice] = 'Registration request rejected successfully'
  end

  def remove_users
    registration = Registration.where(academy_id: params[:id],
                                      user_id: params[:user_id]).first
    registration.destroy
    flash[:notice] = 'User registration removed successfully.'
    redirect_to :back
  end

  private

  def academy_permitted_params
    params.require(:academy).permit!
  end
end

app/helpers/academies_helper.rb
module AcademiesHelper # :nodoc:
end

app/views/academies/_approved_academy_list.html.erb
<%if @academies.present? %>
	<h4><strong>Academy List</strong></h4>(Which have user successfully register.)
	<table class="table table-striped table-hover">
		<thead>
			<th>
				<strong>Index</strong>
			</th>
			<th>
				<strong>Academy Name</strong>
			</th>
			<th>
				<strong>Owner Name</strong>
			</th>
			<th>
				<strong>Moderater Names</strong>
			</th>
			<th>
				<strong>Description</strong>
			</th>
		</thead>
		<tbody>
			<% @academies.each_with_index do |academy, index| %>
				<tr>
					<td>
						<%= index+1 %>.
					</td>
					<td>
						<%= academy.name.humanize %>
					</td>
					<td>
						<%= academy.owner.full_name %>
					</td>
					<td>
						<%= academy.moderators.map(&:first_name).join(", ") %>
					</td>
					<td>
						<%= academy.description %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

<%if @assignments.present? %>
	<h4><strong>Assignment List</strong></h4>
	<table class="table table-striped table-hover">
		<thead>
			<th>
				<strong>Index</strong>
			</th>
			<th>
				<strong>Academy Name</strong>
			</th>
			<th>
				<strong>Assignment Name</strong>
			</th>
			<th>
				<strong>Assignment Type</strong>
			</th>
			<th>
				<strong>Descriptiomn</strong>
			</th>
			<th>
				<strong>Due Date</strong>
			</th>
		</thead>
		<tbody>
			<% @assignments.each_with_index do |assignment, index| %>
				<tr>
					<td>
						<%= index+1 %>.
					</td>
					<td>
						<%= assignment.academy.name.humanize %>
					</td>
					<td>
						<%= link_to assignment.title, academy_assignment_path(assignment.academy, assignment) %>
					</td>
					<td>
						<%= assignment.assignment_type %>
					</td>
					<td>
						<%= assignment.description %>
					</td>
					<td>
						<%= assignment.due_date.strftime("%d/%m/%Y") %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/academies/_form.html.erb
<%= simple_nested_form_for(@academy, url: (@academy.new_record? ? new_payment_payments_path : academy_path(@academy)), method: (@academy.new_record? ? :post : :put)) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-inputs">
        <%= f.input :name, required: true, placeholder: "Acedemy Name", input_html: {class: 'form-control'} %>
      </div>
    </div>
  </div>

  <%= f.fields_for :subscription do |s| %>
    <div class="row">
      <div class="col-md-6">
        <div class="form-inputs">
          <%= s.input :plan_id, collection: Plan::plan_select_options, as: :select, label: "Choose plan(price)", include_blank: false, prompt: "Select Plan", input_html: {class: 'form-control' } %>
          <%= s.input :institution_id, as: :hidden, label: false, input_html: {class: 'form-control', value: current_user.id } %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-inputs">
        <%= f.input :description, required: true, placeholder: "Enter description about Acedemy", input_html: {class: 'form-control'} %>
      </div>
    </div>
  </div>

  </br>
  
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.button :submit, (@academy.new_record? ? "Next" : "Update"), class: 'btn btn-primary', data: {disable_with: "Please Wait..."}  %>
      </div>
    </div>
  </div>
<% end %>

app/views/academies/_institution_academy_list.html.erb
<% if @academies.present? %>
	<div class="row">
		<div class="col-md-10">
			<h2>Academy List</h2>
		</div>
		<div class="col-md-2">
			<%= link_to "New Academy", new_academy_path, class: "btn btn-primary" %>
		</div>
	</div>
	<hr>
	<table class="table table-striped table-hover">
		<thead>
			<th>
				<strong>Index</strong>
			</th>
			<th>
				<strong>Academy Name</strong>
			</th>
			<th>
				<strong>Institution Name</strong>
			</th>
			<th>
				<strong>Owner Name</strong>
			</th>
			<th>
				<strong>Moderator Names</strong>
			</th>
			<th>
				<strong>Description</strong>
			</th>
			<th>
				<strong>Date Created</strong>
			</th>
			<th>
				<strong>Action</strong>
			</th>
		</thead>
		<tbody>
			<% @academies.each_with_index do |academy, index| %>
				<tr>
					<td>
						<%= index+1 %>.
					</td>
					<td>
						<% if ((current_user.is_owner? academy)||(current_user.is_registered? academy)) %>
							<%= link_to academy.name.humanize, academy_path(academy) %>
						<% else %>
							<%= academy.name.humanize %>
						<% end %>
					</td>
					<td>
						<%= academy.owner.institution_name %>
					</td>
					<td>
						<%= academy.owner.full_name %>
					</td>
					<td>
						<%= academy.moderators.pluck(:first_name).join(", ") %>
					</td>
					<td>
						<%= academy.description.truncate(20) %>
					</td>
					<td>
						<%= academy.created_at.strftime("%d/%m/%Y") %>
					</td>
					<td>
						<% if current_user.is_pending? academy %>
							Request Already Pending. 
						<% elsif current_user.is_registered? academy %>
							Already Registered.
						<% elsif current_user.is_owner? academy %>
							You owned that academy.
						<% else %>
							<%= link_to "Register as Moderator", send_joining_request_academy_path(academy), class: "btn btn-primary register_request", data: { disable_with: "please wait..." } %>
						<% end %>
						<% if ((current_user.is_owner? academy)||(current_user.is_registered? academy)) %>
							|
							<%= link_to "Edit", edit_academy_path(academy) %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/academies/_registration_list.html.erb
<%if @standard_registrations.present? %>
	<h3>Student Registraion Requests</h3>
	<table class="table table-striped table-hover">
		<thead>
			<th>
				<strong>Index</strong>
			</th>
			<th>
				<strong>Academy Name</strong>
			</th>
			<th>
				<strong>Requester Name</strong>
			</th>
			<th>
				<strong>Registration Status</strong>
			</th>
			<th>
				<strong>Action</strong>
			</th>
		</thead>
		<tbody>
			<% @standard_registrations.each_with_index do |reg, index| %>
				<tr>
					<td>
						<%= index+1 %>.
					</td>
					<td>
						<%= reg.academy.name.try(:humanize) %>
					</td>
					<td>
						<%= reg.user.full_name %>
					</td>
					<td>
						<%= reg.status %>
					</td>
					<td>
						<% if reg.status == "pending" %>
							<%= link_to "Approve", approve_registration_request_academy_path(reg), remote: true %> | 
						<% end %>
						<%= link_to "Reject", remove_registration_request_academy_path(reg), method: :delete, remote: true %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

</br>

<%if @institution_registrations.present? %>
	<h3>Moderator Registraion Requests</h3>
	<table class="table table-striped table-hover">
		<thead>
			<th>
				<strong>Index</strong>
			</th>
			<th>
				<strong>Academy Name</strong>
			</th>
			<th>
				<strong>Requester Name</strong>
			</th>
			<th>
				<strong>Registration Status</strong>
			</th>
			<th>
				<strong>Action</strong>
			</th>
		</thead>
		<tbody>
			<% @institution_registrations.each_with_index do |reg, index| %>
				<tr>
					<td>
						<%= index+1 %>.
					</td>
					<td>
						<%= reg.academy.name.try(:humanize) %>
					</td>
					<td>
						<%= reg.user.full_name %>
					</td>
					<td>
						<%= reg.status %>
					</td>
					<td>
						<% if reg.status == "pending" %>
							<%= link_to "Approve", approve_registration_request_academy_path(reg), remote: true %> | 
						<% end %>
						<%= link_to "Reject", remove_registration_request_academy_path(reg), method: :delete, remote: true %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/academies/_standard_academy_list.html.erb
<% if @academies.present? %>
	<div class="row">
		<div class="col-md-10">
			<h2>Academy List</h2>
		</div>
	</div>
	<hr>
	<table class="table table-striped table-hover">
		<thead>
			<th>
				<strong>Index</strong>
			</th>
			<th>
				<strong>Academy Name</strong>
			</th>
			<th>
				<strong>Institution Name</strong>
			</th>
			<th>
				<strong>Owner Name</strong>
			</th>
			<th>
				<strong>Moderator Names</strong>
			</th>
			<th>
				<strong>Description</strong>
			</th>
			<th>
				<strong>Date Created</strong>
			</th>
			<th>
				<strong>Action</strong>
			</th>
		</thead>
		<tbody>
			<% @academies.each_with_index do |academy, index| %>
				<tr>
					<td>
						<%= index+1 %>.
					</td>
					<td>
						<%= academy.name.humanize %>
					</td>
					<td>
						<%= academy.owner.institution_name %>
					</td>
					<td>
						<%= academy.owner.full_name %>
					</td>
					<td>
						<%= academy.moderators.pluck(:first_name).join(", ") %>
					</td>
					<td>
						<%= academy.description.truncate(20) %>
					</td>
					<td>
						<%= academy.created_at.strftime("%d/%m/%Y") %>
					</td>
					<td>
						<% if current_user.is_pending? academy %>
							Request Already Pending. 
						<% elsif current_user.is_registered? academy %>
							Already Registered.
						<% else %>
							<%= link_to "Register", send_joining_request_academy_path(academy), class: "btn btn-primary register_request", data: { disable_with: "please wait..." } %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/academies/academies_lists.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>Academy List</h1>
		</div>
	</div>
	<div id="academy_contents">		
		<%= render "academy_list" %>
	</div>		
</div>	

app/views/academies/approve_registration_request.js.erb
$("#registration_contents").html('<%= escape_javascript( render partial: "registration_list") %>');
show_flash('<%= flash_message(flash) %>');
<% flash.clear %>

app/views/academies/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h1>Academy Details</h1>
		</div>
		<div class="col-md-2">
			<%= link_to "New Assignment", new_academy_assignment_path(@academy), class: "btn btn-primary" %>
		</div>
	</div>
	<div id="academy_detail_contents">
		<%= render "form" %>		
	</div>		
</div>	

app/views/academies/index.html.erb
<div class="container">
	<% if current_user.is_institution_user? %>
		<%= render "institution_academy_list" %>
	<% else %>
		<%= render "standard_academy_list" %>
	<% end %>
</div>

app/views/academies/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Create New Academy</h1>
    </div>
  </div>
  <div class="new_academy">
    <%= render "form" %>
  </div>
</div>

app/views/academies/registration_list.html.erb
<h2>List of Registrations</h2>
<div id="registration_contents">
	<%= render "registration_list" %>
</div>

app/views/academies/remove_registration_request.js.erb
$("#registration_contents").html('<%= escape_javascript( render partial: "registration_list") %>');
show_flash('<%= flash_message(flash) %>');
<% flash.clear %>

app/views/academies/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h1>Academy Details</h1>
		</div>
		<div class="col-md-2">
			<%= link_to "New Assignment", new_academy_assignment_path(@academy), class: "btn btn-primary" %>
		</div>
	</div>
	<% if @academy.present? %>
		<div id="academy_detail_contents">
			<div class="own_academies">
				<div class="row">
					<div class="col-md-6">
						<h3><strong>Owned Academies</strong></h3>
					</div>
				</div>
			  <div class="row">
			  	<div class="col-md-3">
			  		Academy Name: <%= @academy.name %>
			  	</div>
		  	</div>
			 	<div class="row">
			 		Description: <%= @academy.description %>
			 	</div>
			</div>
		</div>
		<% if @assignments.present? %>
			<div class="assignments">
				<div class="row">
					<div class="col-md-6">
						<h3><strong>Assignments</strong></h3>
					</div>
				</div>
				<table class="table table-striped table-hover">
					<thead>
						<th>Index</th>
						<th>Assignment Title</th>
						<th>Academy Name</th>
						<th>Assignment completion count</th>
						<th>Assignment not completion count</th>
						<th>Action</th>
					</thead>
					<tbody>
						<% @assignments.each_with_index do |assignment, index| %>
							<tr>
								<td><%= index+1 %>.</td>
								<td><%= assignment.title %></td>
								<td><%= assignment.academy.name %></td>
								<td><%= 0 %></td>
								<td><%= 0 %></td>
								<td><%= link_to "Edit", edit_academy_assignment_path(assignment.academy, assignment) %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		<% end %>

		<% if @students.present? %>
			<div class="students">
				<div class="row">
					<div class="col-md-6">
						<h3><strong>Students</strong></h3>
					</div>
				</div>
				<table class="table table-striped table-hover">
					<thead>
						<th>Index</th>
						<th>Student Name</th>
						<th>Total Purchases</th>
						<th>Total Sales</th>
						<th>Total Earning</th>
						<th>Action</th>
					</thead>
					<tbody>
						<% @students.each_with_index do |student, index| %>
							<tr>
								<td><%= index+1 %>.</td>
								<td><%= student.full_name %></td>
								<td><%= student.total_purchase %></td>
								<td><%= student.total_sales %></td>
								<td><%= student.total_earning %></td>
								<td><%= link_to "Delete", remove_users_academy_path(@academy, user_id: student.id), method: :delete %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		<% end %>

		<% if @moderators.present? %>
			<div class="moderators">
				<div class="row">
					<div class="col-md-6">
						<h3><strong>Moderators</strong></h3>
					</div>
				</div>
				<table class="table table-striped table-hover">
					<thead>
						<th>Index</th>
						<th>Moderator Name</th>
						<th>Action</th>
					</thead>
					<tbody>
						<% @moderators.each_with_index do |moderator, index| %>
							<tr>
								<td><%= index+1 %>.</td>
								<td><%= moderator.full_name %></td>
								<td><%= link_to "Delete", remove_users_academy_path(@academy, user_id: moderator.id), method: :delete %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		<% end %>

		<% if @student_requests.present? %>
			<div class="student_requests">
				<div class="row">
					<div class="col-md-6">
						<h3><strong>User Requests</strong></h3>
					</div>
				</div>
				<table class="table table-striped table-hover">
					<thead>
						<th>Index</th>
						<th>Academy Name</th>
						<th>User Name</th>
						<th>Action</th>
					</thead>
					<tbody>
						<% @student_requests.each_with_index do |request, index| %>
							<tr>
								<td><%= index+1 %>.</td>
								<td><%= request.academy.name %></td>
								<td><%= request.user.full_name %></td>
								<td><%= link_to "Accept", approve_registration_request_academy_path(reg), remote: true  %> | <%= link_to "Decline", remove_registration_request_academy_path(reg), method: :delete, remote: true %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		<% end %>

		<% if @moderator_requests.present? %>
			<div class="moderator_requests">
				<div class="row">
					<div class="col-md-6">
						<h3><strong>Moderator Requests</strong></h3>
					</div>
				</div>
				<table class="table table-striped table-hover">
					<thead>
						<th>Index</th>
						<th>Academy Name</th>
						<th>User Name</th>
						<th>Action</th>
					</thead>
					<tbody>
						<% @moderator_requests.each_with_index do |request, index| %>
							<tr>
								<td><%= index+1 %>.</td>
								<td><%= request.academy.name %></td>
								<td><%= request.user.full_name %></td>
								<td><%= link_to "Accept", approve_registration_request_academy_path(reg), remote: true  %> | <%= link_to "Decline", remove_registration_request_academy_path(reg), method: :delete, remote: true %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		<% end %>
	<% end %>		
</div>	