config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'landings/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  get "details" => "users#user_profile",   as: :user_profile_users
  resources :users, only: [:update]

  resources :academies do
    resources :assignments
    collection do
      get :academies_lists
      get :registration_list
    end
    member do
      get :send_joining_request
      get :approve_registration_request
      delete :remove_registration_request
      delete :remove_users
    end
  end

  resources :payments do
    collection do
      post :new_payment
    end
  end

  resources :portfolios do 
    member do 
      get :fetch_current_price
      get :change_status
    end
  end

  resources :companies do
    resources :purchases
    resources :sales 
  end
  
  resources :articles 
  resources :landings, path: "/" do
    collection do
      post :search  
    end
  end


  root 'landings#index'
end

app/controllers/landings_controller.rb
# rubocop:disable Metrics/AbcSize
class LandingsController < ApplicationController
  def index
    @data = []
    if current_user.present?
      if current_user.is_standard_user?
        if current_user.first_name.present?
          @active_portfolio = current_user.active_portfolio
          @data = current_user.fetch_quandl_data(@active_portfolio)
          @academies = current_user.registrations.where(status: 'approve').map(&:academy).flatten
          @assignments = @academies.map(&:assignments).flatten
        else
          redirect_to user_profile_users_path
        end
      elsif current_user.is_institution_user?
        @owned_academies = current_user.academies
        @mod_academies = current_user.institution_registered_academies
        @student_requests = current_user.registrations.where(reg_type: 'Standard', status: 'pending')
        @moderator_requests = current_user.registrations.where(reg_type: 'Institution', status: 'pending')
        @assignments = current_user.academies.map(&:assignments).flatten
        @moderator_assignments = current_user.institution_registered_academies.map(&:assignments).flatten
      end
    end
  end

  def search
    if params[:category] == 'Company'
      path = companies_path(search: params[:search], category: params[:category])
    elsif params[:category] == 'Academy'
      path = academies_path(search: params[:search], category: params[:category])
    elsif params[:category] == 'Article'
      path = articles_path(search: params[:search], category: params[:category])
    end
    redirect_to path
  end
end

app/helpers/landings_helper.rb
module LandingsHelper # :nodoc:
end

app/views/landings/_article_contents.html.erb
<% if @articles.present? %>
	<table class="table table-striped table-hover">
		<thead>
			<th>Index</th>
			<th>title</th>
			<th>Summary</th>
		</thead>
		<tbody>
			<% @articles.each_with_index do |article, index| %>
				<tr>
					<td><%= index+1 %>.</div>
					<td><%= link_to article.title, learning_lounge_detail_landing_path(article) %></td>
					<td><%= article.summary.truncate(20).html_safe %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p> No Article present in this list </p>
<% end %>

app/views/landings/_company_contents.html.erb
<% if @companies.present? %>
	<table class="table table-striped table-hover">
		<thead>
			<th>Index</th>
			<th>Company Name</th>
			<th>city</th>
			<th>State</th>
			<th>Action</th>
		</thead>
		<tbody>
			<% @companies.each_with_index do |company, index| %>
				<tr>
					<td><%= index+1 %>.</div>
					<td><%= company.name %></td>
					<td><%= company.city %></td>
					<td><%= company.state %></td>
					<td><%= link_to "Company Details", company_details_landing_path(company) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/landings/_institution_user_dashboard.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2 pull-right">
			<%= link_to "New Academy", new_academy_path, class: "btn btn-primary" %>
		</div>
	</div>
	<% if @owned_academies.present? %>
		<div class="own_academies">
			<div class="row">
				<div class="col-md-6">
					<h3><strong>Owned Academies</strong></h3>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<th>Index</th>
					<th>Academy Name</th>
					<th>Status</th>
				</thead>
				<tbody>
					<% @owned_academies.each_with_index do |academy, index| %>
						<tr>
							<td><%= index+1 %>.</td>
							<td><%= link_to academy.name, academy_path(academy) %></td>
							<td><%= "Owner" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>

	<% if @mod_academies.present? %>
		<div class="moderate_academies">
			<div class="row">
				<div class="col-md-6">
					<h3><strong>Moderated Academy</strong></h3>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<th>Index</th>
					<th>Academy Name</th>
					<th>Status</th>
				</thead>
				<tbody>
					<% @mod_academies.each_with_index do |academy, index| %>
						<tr>
							<td><%= index+1 %>.</td>
							<td><%= link_to academy.name, academy_path(academy) %></td>
							<td><%= "Moderator" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>

	<% if @student_requests.present? %>
		<div class="student_requests">
			<div class="row">
				<div class="col-md-6">
					<h3><strong>User Requests</strong></h3>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<th>Index</th>
					<th>Academy Name</th>
					<th>User Name</th>
					<th>Action</th>
				</thead>
				<tbody>
					<% @student_requests.each_with_index do |request, index| %>
						<tr>
							<td><%= index+1 %>.</td>
							<td><%= request.academy.name %></td>
							<td><%= request.user.full_name %></td>
							<td><%= link_to "Accept", approve_registration_request_academy_path(reg), remote: true  %> | <%= link_to "Decline", remove_registration_request_academy_path(reg), method: :delete, remote: true %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>

	<% if @moderator_requests.present? %>
		<div class="moderator_requests">
			<div class="row">
				<div class="col-md-6">
					<h3><strong>Moderator Requests</strong></h3>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<th>Index</th>
					<th>Academy Name</th>
					<th>User Name</th>
					<th>Action</th>
				</thead>
				<tbody>
					<% @moderator_requests.each_with_index do |request, index| %>
						<tr>
							<td><%= index+1 %>.</td>
							<td><%= request.academy.name %></td>
							<td><%= request.user.full_name %></td>
							<td><%= link_to "Accept", approve_registration_request_academy_path(reg), remote: true  %> | <%= link_to "Decline", remove_registration_request_academy_path(reg), method: :delete, remote: true %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>

	<% if @assignments.present? %>
		<div class="assignments">
			<div class="row">
				<div class="col-md-6">
					<h3><strong>Assignments as Owner</strong></h3>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<th>Index</th>
					<th>Assignment Title</th>
					<th>Academy Name</th>
					<th>Assignment completion count</th>
					<th>Assignment not completion count</th>
				</thead>
				<tbody>
					<% @assignments.each_with_index do |assignment, index| %>
						<tr>
							<td><%= index+1 %>.</td>
							<td><%= assignment.title %></td>
							<td><%= assignment.academy.name %></td>
							<td><%= 0 %></td>
							<td><%= 0 %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>

	<% if @moderator_assignments.present? %>
		<div class="moderator_assignments">
			<div class="row">
				<div class="col-md-6">
					<h3><strong>Assignment as Moderator</strong></h3>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<th>Index</th>
					<th>Assignment Title</th>
					<th>Academy Name</th>
					<th>Assignment completion count</th>
					<th>Assignment not completion count</th>
				</thead>
				<tbody>
					<% @moderator_assignments.each_with_index do |assignment, index| %>
						<tr>
							<td><%= index+1 %>.</td>
							<td><%= assignment.title %></td>
							<td><%= assignment.academy.name %></td>
							<td><%= 0 %></td>
							<td><%= 0 %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% end %>
</div>

app/views/landings/_standard_user_dashboard.html.erb
<% if @active_portfolio.present? %>
	<%= render "/portfolios/portfolio_details" %>
	</br>
	<%= render "/academies/approved_academy_list" %>
<% end %>

app/views/landings/article_search.js.erb
$("#article_contents").html('<%= escape_javascript( render partial: "article_contents") %>');

app/views/landings/company_details.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1><strong>Company Details</strong></h1>
		</div>
	</div>
	<div id="company_details">		
		<%= render "company_details" %>
	</div>		
</div>		

app/views/landings/index.html.erb
<div class="container">
	<% if user_signed_in? %>
		<% if current_user.is_standard_user? %>
			<%= render "standard_user_dashboard" %>
		<% elsif current_user.is_institution_user? %>
			<%= render "institution_user_dashboard" %>
		<% end %>
	<% else %>
		<h1>Welcome to Wall Street Ninja</h1>
		<p>If you are already login, please <%= link_to "Sign In", new_user_session_path() %>, Otherwise please <%= link_to "Sign Up", new_user_registration_path %> First.</p>
	<% end %>
</div>

app/views/landings/learning_lounge.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>Article List</h1>
		</div>
		<div class="col-md-6">
			<%= form_tag("/landings/article_search", method: :get, remote: true) do %>
				<div class="form-inputs">
          <%= text_field_tag "search", "", placeholder: "Article Title Or Summary", class: "form-control wdt60" %>
          <%= submit_tag "Search", class: "btn btn-primary" %>
        </div>
      <% end %>
		</div>
	</div>
	<div id="article_contents">		
		<%= render "article_contents" %>
	</div>		
</div>		

app/views/landings/learning_lounge_detail.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>Article Details</h1>
		</div>
	</div>
	<div id="article_contents">		
		<% if @article.present? %>
			<h2><strong><%= @article.title %></strong></h2>
			<%= @article.summary.html_safe %>
		<% end %>
	</div>		
</div>		