config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'landings/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  get "details" => "users#user_profile",   as: :user_profile_users
  resources :users, only: [:update]

  resources :academies do
    resources :assignments
    collection do
      get :academies_lists
      get :registration_list
    end
    member do
      get :send_joining_request
      get :approve_registration_request
      delete :remove_registration_request
      delete :remove_users
    end
  end

  resources :payments do
    collection do
      post :new_payment
    end
  end

  resources :portfolios do 
    member do 
      get :fetch_current_price
      get :change_status
    end
  end

  resources :companies do
    resources :purchases
    resources :sales 
  end
  
  resources :articles 
  resources :landings, path: "/" do
    collection do
      post :search  
    end
  end


  root 'landings#index'
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base # :nodoc:
  belongs_to :user
  has_many :bonuses, class_name: 'Bonus', foreign_key: :portfolio_id,
                     dependent: :destroy

  has_many :stocks, dependent: :destroy
  has_many :sales, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :companies, -> { distinct }, through: :stocks, class_name: 'Company',
                                        foreign_key: 'company_id'

  validates :name, :user_id, presence: true
  validates_inclusion_of :active, in: [true, false]
  accepts_nested_attributes_for :purchases, allow_destroy: true
  default_scope { order('created_at DESC') }

  def update_purchase(purchase, quantity)
    if purchase.quantity > quantity
      total_stock = purchase.quantity - quantity
      total_price = total_stock * purchase.price
      purchase.update_attributes(quantity: total_stock,
                                 total_price: total_price)
    elsif purchase.quantity == quantity
      purchase.destroy
    end
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController # :nodoc:
  before_action :authenticate_user!

  def index
    @active_portfolio = current_user.active_portfolio
    @data = current_user.fetch_quandl_data(@active_portfolio)
  end

  def companies
    @companies = Company.all
  end

  def company_details
    @company = Company.find(params[:id])
  end

  private

  def portfolio_permitted_params
    params[:portfolio][:user_id] = current_user.id
    params.require(:portfolio).permit!
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper # :nodoc:
end

app/views/portfolios/_portfolio_contents.html.erb
<% if @data.present? %>
	<div class="row">
		<table class="table table-striped table-hover">
			<thead>
				<th>Company</th>
				<th>Current price</th>
				<th>Quantity owned</th>
				<th>Purchased price</th>
				<th>Date purchased</th>
				<th>Overall gain</th>
				<th>Action</th>
			</thead>
			<tbody>
				<% @data.each_with_index do |purchase, index| %>
					<tr>
						<td><%= link_to purchase[:company_name], company_path(purchase[:company_id]) %></td>
						<td><%= purchase[:live_price] %></td>
						<td><%= purchase[:quantity] %></td>
						<td><%= purchase[:inv_price] %></td>
						<td><%= purchase[:inv_date] %></td>
						<td><%= purchase[:overall_gain] %></td>
						<td><%= link_to "Sell", new_company_sale_path(purchase[:company_id], purchase_id: purchase[:purchase_id]), remote: true %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
<% end %>

app/views/portfolios/_portfolio_details.html.erb
<div class="row">
	<div class="col-md-4">
		<span><h2 class="dis_inlne"><%= link_to @active_portfolio.name.titleize, portfolios_path %></h2>(<%= current_user.total_balance %>)</span>
	</div>
</div>

<div class="row">
	<table class="table table-striped table-hover">
		<thead>
			<th>Company</th>
			<th>Quantity Owned</th>
			<th>Price Purchased</th>
			<th>Current Price</th>
		</thead>
		<tbody>
			<% @data.each_with_index do |purchase, index| %>
				<tr>
					<td><%= link_to purchase[:company_name], company_path(purchase[:company_id]) %></td>
					<td><%= purchase[:quantity] %></td>
					<td><%= purchase[:inv_price] %></td>
					<td><%= purchase[:live_price] %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/portfolios/change_status.js.erb
$("#portfolio_contents").html('<%= escape_javascript( render partial: "portfolio_contents") %>');
show_flash('<%= flash_message(flash) %>');
<% flash.clear %>

app/views/portfolios/fetch_current_price.js.erb
var price = <%= @price %>;
$("#price_<%= params[:index]%>").val(price);
$(".filter_loader").addClass("dis_none");

app/views/portfolios/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h1>Portfolio</h1>
		</div>
		<div class="col-md-2">
			<span class="pull-right"><%#= link_to "Create New Portfolio", new_portfolio_path, class: "btn btn-primary mr_top" %></span>
		</div>
	</div>
	<div id="portfolio_contents">		
		<%= render "portfolio_contents" %>
	</div>		
</div>		

app/views/portfolios/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Portfolio</h1>
    </div>
  </div>
  <%= simple_nested_form_for(@portfolio, url: (@portfolio.new_record? ? portfolios_path : portfolio_path(@portfolio)), method: (@portfolio.new_record? ? :post : :put)) do |f| %>
    <div class="row">
      <div class="col-md-6">
        <div class="form-inputs">
          <%= f.input :name, required: true, placeholder: "Portfolio Name", input_html: {class: 'form-control'} %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :balance, label: "Total", placeholder: "0",  input_html: { class: 'form-control', value: (@portfolio.new_record? ? 0 : f.object.balance), readonly: true } %>
        </div>
      </div>
    </div>

    <%= f.fields_for :purchases do |st| %>
      <div class="row">
        <%= st.input :type, as: :hidden, label: false, input_html: { value: "Purchase", class: 'form-control' } %>

        <div class="col-md-3">
          <div class="form-group">
            <%= st.input :company_id, collection: Company.all.map{|c| [c.name, c.id]}, as: :select, required: true, label: "Company", include_blank: false,prompt: "Select Company", input_html: {class: 'form-control select_company', "data-attr" => st.options[:child_index], readonly: (st.object.new_record? ? false : true) } %>
          </div>
        </div>

        <div class="col-md-3">
          <div class="form-group">
            <%= st.input :price, required: true, label: "Price", placeholder: "Price", input_html: { class: 'form-control live_price', id: "price_#{st.options[:child_index]}", readonly: true } %>
          </div>
        </div>

        <div class="col-md-3">
          <div class="form-group">
            <%= st.input :quantity, required: true, label: "Quantity", placeholder: "Enter Quantity",  input_html: { class: 'form-control enter_quantity', "data-attr" => st.options[:child_index], readonly: (st.object.new_record? ? false : true) } %>
          </div>
        </div>  

        <div class="col-md-3">
          <div class="form-group">
            <%= st.input :total_price, required: true, label: "Total Price", placeholder: "Total Price",  input_html: { class: 'form-control total_price', id: "total_price_#{st.options[:child_index]}", readonly: true} %>
          </div>
        </div>
        <!-- <div class="col-md-1">
          <%#= st.link_to_remove(href: "javascript:void(0)", class: "close_icon", id: "rm_port") do %>
            <%#= image_tag 'input_icon.png', width: 10, height: 10 %>
          <%# end %>
        </div> -->
      </div>
    <% end %>
    <%= f.link_to_add "+Add More Company", :purchases, style: "float: right;" %>

    <div class="row">
      <div class="col-md-3">
        <div class="form-group">
          <%= f.button :submit, "Create Portfolio", class: 'btn btn-primary', data: {disable_with: "Please Wait..."}  %>
        </div>
      </div>
    </div>
  <% end %>
</div>