config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'landings/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  get "details" => "users#user_profile",   as: :user_profile_users
  resources :users, only: [:update]

  resources :academies do
    resources :assignments
    collection do
      get :academies_lists
      get :registration_list
    end
    member do
      get :send_joining_request
      get :approve_registration_request
      delete :remove_registration_request
      delete :remove_users
    end
  end

  resources :payments do
    collection do
      post :new_payment
    end
  end

  resources :portfolios do 
    member do 
      get :fetch_current_price
      get :change_status
    end
  end

  resources :companies do
    resources :purchases
    resources :sales 
  end
  
  resources :articles 
  resources :landings, path: "/" do
    collection do
      post :search  
    end
  end


  root 'landings#index'
end

app/views/shared/_filter_page.html.erb
<%= form_tag("search") do %>
  <div class="form-inputs">
    <%= select_tag "category", options_for_select(User::SEARCH_CATAGORIES, params[:category]), required: true, prompt: "Choose search options", class: "wdt60 mrht6"  %>
    <%= text_field_tag "search", (params[:search].present? ? params[:search] : ""), required: true, placeholder: "Searching text...", class: "wdt60", autocomplete: "off" %>
    <%= submit_tag "Search", class: "btn btn-primary search_btn" %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
	<div class="container">
	  <div class="filter_loader dis_none">
   		<%= image_tag "search_loader.gif" %>
    </div>
	</div>
</footer>

app/views/shared/_header.html.erb
<div class="page-header">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>0
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" data-no-turbolink="true">Wall Street Ninja</a>
      </div>
      
      <div class="col-md-5 mtop9">
        <% if user_signed_in? %>
          <%= render "shared/filter_page" %>
        <% end %>
      </div>
      
      <div id="navbar" class="collapse navbar-collapse pull-right">
        <ul class="nav navbar-nav">
          <% if !user_signed_in? %>
            <li><a href="/login">SignIn</a></li>
            <li><a href="/signup">SignUp</a></li>
          <% elsif current_user.is_standard_user? %>
            <%= render "/shared/standard_user_header" %>
          <% else %>
            <%= render "/shared/institution_user_header" %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_institution_user_header.html.erb
<li>
  <%= link_to "Registrations", registration_list_academies_path %>
</li>
<li>
  <%= link_to "Company", companies_path %>
</li>
<li>
  <%= link_to "Learning Lounge", articles_path %>
</li>
<li>
  <%= link_to "Academies", academies_path %>
</li>
<li>
  <%= link_to "SignOut", destroy_user_session_path, method: :delete %>
</li>

app/views/shared/_notification.html.erb
<script>
    var message = "<%=flash.to_hash.values.join(", ")%>"
    $(function () {
        $.growl({
            title: "",
            message: message,
            namespace: "growl",
            duration: 5000,
            close: "&#215;",
            location: "tc",
            style: "default",
            size: "medium",
        });
    });
</script>

app/views/shared/_standard_user_header.html.erb
<% if current_user.first_name.present?%>
  <li>
    <%= link_to "Portfolio", portfolios_path %>
  </li>
  <li>
    <%= link_to "Company", companies_path %>
  </li>
  <li>
    <%= link_to "Learning Lounge", articles_path %>
  </li>
  <li>
    <%= link_to "Academies", academies_path %>
  </li>
<% end %>

<li>
  <%= link_to "SignOut", destroy_user_session_path, method: :delete %>
</li>